mnrendra/stack-trace

.github/workflows/release.yml, jest.config.ts, package-lock.json, package.json
issues:
* chore/standardize-chores (#15)
commits:
* chore/standardize-chores (69604e9)
=> chore: standardize chores

jest.config.ts, src/index.test.ts, src/main.test.ts, src/utils/createTarget.test.ts, src/utils/index.test.ts, tests/stubs/index.ts, tests/stubs/main.ts, tests/stubs/target.ts, tsconfig.json
issues:
* test: update unit tests (#19)
commits:
* test: update unit tests (e6afb77)
=> test: update unit tests

src/main.ts, src/utils/createTarget.ts
issues:
* docs: update code comments (#21)
commits:
* docs: update code comments (a5329d0)
=> docs: update code comments

README.md
issues:
* hotfix: v1.2.1 (#33)
commits:
* fix: readme (#35) (3d2ae98)
=> hotfix: v1.2.1

README.md, package-lock.json, package.json, src/index.ts
issues:
* feat: drop validate skipped stacks (#37)
commits:
* feat: drop validate skipped stacks (5d17d2a)
=> feat: drop validate skipped stacks

README.md, package-lock.json, package.json, src/index.ts
issues:
* merge: v1.3.0 (#39)
commits:
* feat: drop validate skipped stacks (#38) (7654b36)
=> merge: v1.3.0

README.md, __tests__/index.ts, package-lock.json, package.json, src/index.ts
issues:
* feat: provide validate-skipped-stacks (#43)
commits:
* feat: provide validate-skipped-stacks (90faa6e)
=> feat: provide validate-skipped-stacks

README.md
issues:
* merge: v1.4.1 (#49)
commits:
* docs: update readme (#48) (3334603)
=> merge: v1.4.1

package-lock.json, package.json
issues:
* merge: v1.4.2 (#53)
commits:
* chore: upgrade dependencies (#52) (c73b791)
=> merge: v1.4.2

README.md, package-lock.json, src/index.ts, src/main.ts, src/types/Func.ts, src/types/Options.ts, src/types/index.ts
issues:
* chore: upgrade dependencies (#55)
commits:
* chore: upgrade dependencies (dfa55cf)
=> chore: upgrade dependencies

README.md, __tests__/index.ts, src/libs/traceFiles.ts
issues:
* fix: trace files target (#67)
commits:
* fix: trace files target (2a5d521)
=> fix: trace files target

README.md, __tests__/index.ts, package-lock.json, package.json, src/index.ts, src/libs/index.ts, src/libs/traceFnNames.ts, src/libs/traceStacks.ts, src/types/CallSite.ts
issues:
* feat: trace fn names (#69)
commits:
* feat: trace fn names (1be6d79)
=> feat: trace fn names

README.md, __tests__/index.ts, package-lock.json, package.json, src/index.ts, src/libs/index.ts, src/libs/traceFiles.ts, src/libs/traceFnNames.ts, src/libs/traceStacks.ts, src/types/CallSite.ts
issues:
* merge: v2.1.0 (#71)
commits:
* fix: trace files target (#68) (8b3e8be)
* feat: trace fn names (#70) (e627717)
=> merge: v2.1.0

README.md, __tests__/index.ts, src/index.ts, src/libs/getCallerFile.ts, src/libs/getCallerSite.ts, src/libs/index.ts, src/main.ts
issues:
* feat: get caller file (#82)
commits:
* feat: get caller file (fd1b1f7)
=> feat: get caller file

README.md, package-lock.json, package.json, src/libs/getCallerDir.ts, src/libs/getCallerFile.ts, src/libs/getCallerSite.ts, src/main.ts, src/types/Options.ts, src/utils/extractFilePath.ts
issues:
* docs: update link (#86)
commits:
* docs: update link (f506855)
=> docs: update link

package-lock.json, package.json
issues:
* fix: add semantic release dependencies (#91)
commits:
* fix: add semantic release dependencies (282f6f5)
=> fix: add semantic release dependencies

package-lock.json, package.json
issues:
* hotfix: v3.1.0 (#90)
commits:
* fix: add semantic release dependencies (#92) (2dfca00)
=> hotfix: v3.1.0

package-lock.json, package.json
issues:
* merge: v3.1.1 (#96)
commits
* chore: update package (#95) (2b7dc8c)
=> merge: v3.1.1

.github/workflows/release.yml, .github/workflows/test.yml, package-lock.json, package.json
issues:
* ci: add test (#98)
commits:
* ci: add test (2c72db9)
=> ci: add test

README.md, package-lock.json
issues:
* docs: update readme (#100)
commits:
* docs: update readme (999937c)
=> docs: update readme

.github/workflows/release.yml, .github/workflows/review.yml, .github/workflows/security.yml, .github/workflows/test.yml, .pre-commit-config.yaml, README.md, package-lock.json, package.json
issues:
* merge: v3.1.2 (#108)
commits:
* ci: add test (#99) (b3eb88f)
* docs: update readme (#102) (61cfd33)
* ci: add security (#104) (3213e6f)
* docs: update readme (#107) (8fce946)
* ci: fix test workflows (#111) (b7b6380)
=> merge: v3.1.2

.github/workflows/release.yml, .github/workflows/security.yml
issues:
* ci: fix workflows (#113)
commits:
* ci: fix workflows (30d1315)
=> ci: fix workflows

.github/workflows/release.yml, .github/workflows/security.yml
issues:
* hotfix: v3.1.2 (#112)
commits:
* ci: fix workflows (#114) (3b06c7b)
=> hotfix: v3.1.2

.github/workflows/release.yml, .github/workflows/review.yml, .github/workflows/security.yml, .github/workflows/test.yml
issues:
* ci: fix ossf scorecard workflow (#117)
commits:
* ci: fix ossf scorecard workflow (8c83bda)
=> ci: fix ossf scorecard workflow

.github/workflows/release.yml, .github/workflows/security.yml
issues:
* ci: fix release needs (#121)
commits:
* ci: fix release needs (c7c21b8)
=> ci: fix release needs

.github/workflows/release.yml
issues:
* ci: fix persist credentials (#129)
commits:
* ci: fix persist credentials (80744a7)
=> ci: fix persist credentials

.github/workflows/release.yml
issues:
* hotfix: v3.1.3 (#128)
commits:
* ci: fix persist credentials (#130) (06a3778)
=> hotfix: v3.1.3

.github/dependabot.yml, .github/workflows/audit.yml, .github/workflows/checkpoint.yml, .github/workflows/release.yml, .github/workflows/reusable.codeql.yml, .github/workflows/reusable.release.yml, .github/workflows/reusable.review.yml, .github/workflows/reusable.scorecard.yml, .github/workflows/reusable.test.yml, .npmignore, .npmrc, .pre-commit-config.yaml, .releaserc, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md, package-lock.json, package.json
issues:
* chore: update skeleton (#132)
commits:
* chore: update skeleton (f21ce7b)
* chore: fix reusable workflow paths (b0e6d15)
* chore: fix secrets workflows (08a414a)
* chore: add id-token in release workflows (1b401ae)
=> chore: update skeleton
